[General]
Font="Noto Sans"
FontSize=12
ClockEnabled="true"
CustomBackground="false"
LoginBackground="false"

foreground = "#CFD5FD"
background = "#101022"
prompt     = "#070812"
unfocused  = "#3D3656"
primary_l  = "#FCCAFF"
primary    = "#FFBDF8"
primary_d  = "#FFAAEE"
secondary  = "#FFF1A9"
